# Generated by Django 4.1.1 on 2022-09-18 02:05

from django.db import migrations, models
import scheduler.validators


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_rename_tech_ration_floor_tech_ratio'),
    ]

    operations = [
        migrations.AddField(
            model_name='floor',
            name='short_name',
            field=models.CharField(default='<d', max_length=5, validators=[scheduler.validators.validate_no_space]),
        ),
    ]
